config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  resources:users
  
  get 'home/index'

  get 'home/new'

  post 'home/create'
  
  get 'home/destroy/:post_id' => 'home#destroy'
  
  get 'home/destroy/:post_id' => 'post#destroy', as: 'post_destroy'
  

  get 'home/edit/:post_id' => 'home#edit'

  post 'home/update/:post_id' => 'home#update'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # 테이블 전체를 보여주기
    @posts = Post.all
  end

  def new
  end

  def create #테이블에 채워넣기
    @post = Post.new #테이블의 한 행을 추가
    @post.title = params[:post_title] #post_title이라는 이름의 내용을 title 행 아래 저장
    @post.content = params[:post_content] #post_content이라는 이름의 내용을 content 행 아래 저장
    @post.save #테이블에 써준 내용을 모두 저장
    #.save 후 id가 부여됨
    
    redirect_to '/home/index' #작업이 완료되면 되돌아갈 페이지
  end
  
  def destroy
    #Post.destroy_all #전체 게시물 삭제
    #특정 게시물만 삭제하려면 id를 알아야함
    
    post = Post.find(params[:post_id]) #해당 id를 가진 게시물을 찾아라
    #컨트롤러 내에서만 필요하기 때문에 @를 붙이지 않아도 됨
    post.destroy
    
    redirect_to '/home/index'
  end
  
  def edit
    @post = Post.find(params[:post_id])
    #view 파일에서 작성한 코드를 보여주고 싶을 땐 @를 꼭 붙여야 함
  end
  
  def update
    post = Post.find(params[:post_id])
    post.title = params[:post_title]
    post.content = params[:post_content]
    
    post.save
    
    redirect_to '/home/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    User.create(
      name: params[:name],
      email: params[:email],
      password: params[:password]
      )
      
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/create.html.erb
<%=params%>

app/views/home/destroy.html.erb
<%=params[:post_id]%>번 게시물을 삭제합니다!

app/views/home/edit.html.erb
<h1>글 수정</h1>
<form action='/home/update/<%=@post.id%>' method='post'> 
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
     제목 : <input type="text" name="post_title" value='<%=@post.title%>'><br><br>
     내용 : <textarea name ="post_content"><%=@post.content%></textarea><br><br>
     <input type="submit" value="수정하기">
</form>

app/views/home/index.html.erb
<h1>게시물 목록 페이지</h1>
<a href='/home/new'>새 글 쓰러가기</a>
<br><br><br>

<%@posts.each do |p|%> <!--each : 한 줄 한 줄 불러오기 위해서 -->
<!--p 는 post 테이블의 각 행 -->
    제목 : <%=p.title%><br> <!--루비코드는 =을 붙여줘야함-->
    내용 : <%=p.content%><br>
    <a href='/home/destroy/<%=p.id%>'>[삭제]</a>
    <%=link_to '[삭제2]', "/home/destroy/#{p.id}" %> <!--link_to-->
    
    <%=link_to post_destroy_path(post_id:p.id) do%>
        <button>[삭제3]</button> <!--do end안에 태그 사용 가능-->
    <%end%>
    
    <a href='/home/edit/<%=p.id%>'>[수정]</a><br>
    <!--url로 post id 넘겨줌-->
    -------------------------<br>
<%end%> 
<!--테이블 한 줄 씩 do~end 사이의 작업을 반복-->

app/views/home/new.html.erb
<h1>글 작성</h1>
<form action='/home/create' method='post'> <!--routes의 post/get과 일치하여야 함-->
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %> <!--post방식으로 보낼 때 안전하게-->
     제목 : <input type="text" name="post_title"><br><br>
     내용 : <textarea name ="post_content"></textarea><br><br>
     <input type="submit" value="제출">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=link_to '회원가입', new_user_path%>
<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%=form_tag(users_path, method: "post") do %>
    이름 : <%=text_field_tag 'name' %><br>
    이메일 : <%=text_field_tag 'eamil' %><br>
    비밀번호 : <%=text_field_tag 'password' %><br>
    <input type="submit" value="제출">
<%end%>